============================= test session starts ==============================
platform linux -- Python 3.13.0, pytest-8.3.3, pluggy-1.5.0 -- /ceph/project/milne_group/cchahrou/software/miniforge3/envs/seqnado_dev/bin/python3.13
cachedir: .pytest_cache
rootdir: /ceph/project/milne_group/cchahrou/software/SeqNado
configfile: pyproject.toml
plugins: typeguard-4.3.0
collecting ... collected 1 item

tests/test_pipelines.py::test_config[atac] DEBUG: Writing genome_config.json -> {
    "hg38": {
        "index": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/bt2_chr21_dm6_chr2L/bt2_chr21_dm6_chr2L",
        "chromsizes": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/chr21.fa.fai",
        "gtf": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/chr21.gtf",
        "blacklist": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/hg38-blacklist.v2.bed.gz"
    }
}
ERROR

==================================== ERRORS ====================================
_____________________ ERROR at setup of test_config[atac] ______________________

run_directory = local('/tmp/pytest-of-cchahrou/pytest-8/atac0')
user_inputs = 'project_name=test\ngenome=hg38\nfastq_screen=no\nremove_blacklist=yes\nremove_pcr_duplicates=yes\nremove_pcr_duplicat...ordinates=/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/plotting_coordinates.bed\nplotting_genes=None'
assay_type = 'atac'
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f004aea5220>

    @pytest.fixture(scope="function")
    def config_yaml(run_directory, user_inputs, assay_type, monkeypatch):
        user_inputs = "\n".join([f"{k}={v}" for k, v in user_inputs.items()])
        genome_config_file = run_directory / "genome_config.json"
    
        monkeypatch.setenv("SEQNADO_CONFIG", str(run_directory))
        monkeypatch.setenv("HOME", str(run_directory))
        logger.debug(f"SEQNADO_CONFIG={os.getenv('SEQNADO_CONFIG')}")
        logger.debug(f"HOME={os.getenv('HOME')}")
    
        with open(genome_config_file) as f:
            genome_config = json.load(f)
        logger.debug(f"genome_config contents: {genome_config}")
        logger.debug(f"user_inputs: {user_inputs}")
    
        cmd = ["seqnado-config", assay_type]
        process = subprocess.Popen(
            cmd,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=run_directory,
        )
    
        stdout, stderr = process.communicate(input=user_inputs)
    
        date = datetime.now().strftime("%Y-%m-%d")
        config_file_path = (
            run_directory / f"{date}_{assay_type}_test/config_{assay_type}.yml"
        )
    
>       assert process.returncode == 0, f"seqnado-config failed with stderr: {stderr}"
E       AssertionError: seqnado-config failed with stderr: 2025-02-10 22:15:22.909 | DEBUG    | seqnado.config:setup_configuration:46 - Genome values loaded: {
E             "hg38": {
E                 "index": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/bt2_chr21_dm6_chr2L/bt2_chr21_dm6_chr2L",
E                 "chromsizes": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/chr21.fa.fai",
E                 "gtf": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/chr21.gtf",
E                 "blacklist": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/hg38-blacklist.v2.bed.gz"
E             }
E         }
E         2025-02-10 22:15:22.909 | DEBUG    | seqnado.config:setup_configuration:57 - DEBUG: Extracted genome value: 'genome=hg38'
E         2025-02-10 22:15:22.909 | ERROR    | seqnado.config:setup_configuration:70 - Genome 'genome=hg38' not found in genome config file. Please update the genome config file: /tmp/pytest-of-cchahrou/pytest-8/atac0/genome_config.json
E         2025-02-10 22:15:22.909 | ERROR    | seqnado.config:setup_configuration:70 - Genome 'genome=hg38' not found in genome config file. Please update the genome config file: /tmp/pytest-of-cchahrou/pytest-8/atac0/genome_config.json
E         
E       assert 1 == 0
E        +  where 1 = <Popen: returncode: 1 args: ['seqnado-config', 'atac']>.returncode

tests/test_pipelines.py:366: AssertionError
=========================== short test summary info ============================
ERROR tests/test_pipelines.py::test_config[atac] - AssertionError: seqnado-config failed with stderr: 2025-02-10 22:15:22.909 | DEBUG    | seqnado.config:setup_configuration:46 - Genome values loaded: {
      "hg38": {
          "index": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/bt2_chr21_dm6_chr2L/bt2_chr21_dm6_chr2L",
          "chromsizes": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/chr21.fa.fai",
          "gtf": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/chr21.gtf",
          "blacklist": "/ceph/project/milne_group/cchahrou/software/SeqNado/tests/data/genome/hg38-blacklist.v2.bed.gz"
      }
  }
  2025-02-10 22:15:22.909 | DEBUG    | seqnado.config:setup_configuration:57 - DEBUG: Extracted genome value: 'genome=hg38'
  2025-02-10 22:15:22.909 | ERROR    | seqnado.config:setup_configuration:70 - Genome 'genome=hg38' not found in genome config file. Please update the genome config file: /tmp/pytest-of-cchahrou/pytest-8/atac0/genome_config.json
  2025-02-10 22:15:22.909 | ERROR    | seqnado.config:setup_configuration:70 - Genome 'genome=hg38' not found in genome config file. Please update the genome config file: /tmp/pytest-of-cchahrou/pytest-8/atac0/genome_config.json
  
assert 1 == 0
 +  where 1 = <Popen: returncode: 1 args: ['seqnado-config', 'atac']>.returncode
=============================== 1 error in 0.72s ===============================
